reader:
  app:
    storagePath: storage
    showUI: false
    debug: false
    packaged: false
    secure: false
    inviteCode: ""
    secureKey: ""

  server:
    port: 8080
    webUrl: http://localhost:${reader.server.port}

logging:
  path: "./logs"