reader:
  app:
    storagePath: storage
    showUI: false
    debug: false
    packaged: false

  server:
    port: 8080
    webUrl: http://localhost:${reader.server.port}/web/

logging:
  path: "./logs"